### ISSUE TITLE
"You've Submitted" Number Count

### ISSUE THREAD

**Issue by jenita-thp** [townhallproject/townHallSubmission#29]
The number of events submitted isn't increasing after submitting an event.  My number stayed at 179 after submitting 2 events.

**Comment by Alan-mag** [comment]
Thanks for flagging Jenita, we will look into it.

**Comment by meganrm** [comment]
Move code for incrementing these values to the back end instead of the form

**Comment by meganrm** [comment]
This has been updated and is currently on the beta form. Let me know if something still seems like it's not working.
