### ISSUE TITLE
Page Shift's Left

### ISSUE THREAD

**Issue by jenita-thp** [townhallproject/townHallSubmission#43]
This is the email I got from one of our volunteers Jerry Tobe <tagchai@gmail.com>:
--
I tried shift+refresh. The form still shifted left after pasting an address and clicking any where else on the form. I apologize for mis-information in my earlier e-mail. The form shifts left after entering the address (I copy and paste the address to the form.) and I click any where else on the form. I don't have to enter data in any other field. I've run several tests. The form shifts left at different points in the sequence of entering data and using the "Pg Dn" key. The result is I can't diffinitively say that the form shifts left when information is entered in different sequences. I think the form will always shift left between pasting an address, the date and time and pressing the "Pg Dn" key if the information is entered in the normal sequence. I'm unable to post events at this time.

**Comment by meganrm** [comment]
I think this has been resolved, @Alan-mag, can you confirm?

**Comment by Alan-mag** [comment]
I've heard from Robert that this has been resolved.
