### ISSUE TITLE
Candidate Ed Markey not showing up as option

### ISSUE THREAD

**Issue by nathanmwilliams** [townhallproject/townHallSubmission#73]
Markey is incumbent Senator but also candidate for re-election in MA-Sen

![No candidate Markey](https://user-images.githubusercontent.com/25805849/74461778-f0537c80-4e43-11ea-8ed7-ea6c143aafe3.png)

**Comment by meganrm** [comment]
I added this campaign but you can do this on the admin site. Go to Members of congress, search for his name by clicking the search icon next to 'displayName' and then in his column select "add campaign
